/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id integer GENERATED BY DEFAULT AS IDENTITY primary key,
	name varchar(100),
	date_of_birth date,
	escape_attempt integer,
	neutered boolean,
	weight_kg decimal(13,2),
	species varchar(100)
);

CREATE TABLE owners (
  	id integer GENERATED BY DEFAULT AS IDENTITY primary key,
   	full_name varchar(100),
   	age integer
);

CREATE TABLE species (
 	id integer GENERATED BY DEFAULT AS IDENTITY primary key,
 	name varchar(100)
);

-- Remove column species
ALTER TABLE animals DROP COLUMN species;

-- Add foreign keys column
ALTER TABLE animals ADD species_id int REFERENCES species(id);
ALTER TABLE animals ADD owner_id int REFERENCES owners(id);

